
/* This file is generated by scripts/build_info.py - don't edit it directly!! */

#include "emonTH_build_info.h"

static const char compiler[] = "gcc 12.2.1";
static const char revision[] = "None";
static const char date[] = "11/15/2024 23:22 UTC";
static const char machine[] = "awjlogan@goose-air.lan";
static const char release[] = "None";
static const char build_info[] = "None (Default) on 11/15/2024 23:22 UTC with gcc 12.2.1 by awjlogan@goose-air.lan";

struct EmonTHBuildInfo emonTH_build_info() {
    return (struct EmonTHBuildInfo){
        .revision = revision,
        .date = date,
        .compiler = compiler,
        .machine = machine,
        .release = release,
        .release_year = 0,
        .release_month = 0,
        .release_day = 0,
    };
}

const char* emonTH_build_info_string() { return build_info; }
